### ISSUE TITLE
[BUG] Auto update sending "Update Found!" while using latest version

### ISSUE THREAD

**Issue by czhangdev** [ShieldCommunity/PixelMOTD#30]
**Describe the bug**
Auto update sending "Update Found!" in console while using the latest version.

**Screenshots**
![image](https://user-images.githubusercontent.com/104123210/199384831-3593ce29-080a-4feb-b59b-257c6d36eb77.png)

**System Information (please complete the following information):**
 - Bungeecord
 - 9.3.5 & 10.0.0

**Additional context**
I've tried using latest update from Spigot forum, I've also attempted to use the latest build from CI.

**Comment by xIsm4** [comment]
> **Describe the bug** Auto update sending "Update Found!" in console while using the latest version.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/104123210/199384831-3593ce29-080a-4feb-b59b-257c6d36eb77.png)
> 
> **System Information (please complete the following information):**
> 
> * Bungeecord
> * 9.3.5 & 10.0.0
> 
> **Additional context** I've tried using latest update from Spigot forum, I've also attempted to use the latest build from CI.

I've found that issue tho, we're going to deal with the async-update check.
