### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by WinchesS20** [ShieldCommunity/PixelMOTD#36]
Hello, the plugin is wonderful, but I would like you to add an online cheat so that you can set an online multiplier. For example - 1.5, 2.0, 1.2, etc.

**Comment by MrUniverse44** [comment]
can you explain more about it ?

**Comment by WinchesS20** [comment]
It is necessary to have an online multiplier, for example, in MOTD, where "protocol", add "multiplier: 2.0" - 2.0 is the amount by which the real online will be multiplied, and if possible, then make prefixes on the PROXY server (fake players, as well as come up with nicknames for them) to make it look plausible. And also, so that there is a placeholder, for example "%prixelmotd_server_anarchy1%" - this placeholder will also show the screwed online

**Comment by MrUniverse44** [comment]
so you want the online modifier to be added per-server not only for the proxy, and you want to add the multiplier to the
player-modifiers-list?

And you want a variable to make name for the fake players and to get the multiplier result of a specified server?

**Comment by WinchesS20** [comment]
Yes, or make it so that there is not a multiplier, but how many players you want to add (fake), for example multiplier: 40 players

And all these 40 players were visible on the server, which I will specify in the config, for example on survival

**Comment by MrUniverse44** [comment]
not sure how possible it is to make players see each other on the server and how it will affect to the performance

**Comment by MrUniverse44** [comment]
it is but in the proxy motd for the proxy in general (not per server yet)
